server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tangguo
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

zookeeper:
  address: 127.0.0.1:2181
  timeout: 4000